#!/usr/bin/env bash
# Integration tests for xdl-web using agent-browser
# Usage: ./test-e2e.sh [-q|--quiet] [base-url]
# Requires: agent-browser, running dev server (bun run dev)

set -euo pipefail

QUIET=false
for arg in "$@"; do
  case "$arg" in
    -q|--quiet) QUIET=true; shift ;;
  esac
done

BASE_URL="${1:-http://localhost:5173}"
SESSION="xdl-web-e2e-$$"
REPORT_FILE="test-e2e-failures.log"
PASS=0
FAIL=0

ab() {
  agent-browser --session "$SESSION" "$@"
}

# Reset the failure report
cat > "$REPORT_FILE" <<'HEADER'
# E2E Test Failure Report
# Generated by test-e2e.sh
# Each failure includes: assertion, selector used, page URL, and a DOM snapshot
# to help diagnose whether the issue is a wrong selector, missing element, or timing bug.
HEADER
echo "# Run: $(date -Iseconds)" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

capture_debug() {
  # $1 = test name, $2 = error detail, $3 = selector (optional)
  local url snapshot
  url=$(ab get url 2>/dev/null || echo "(could not get URL)")
  snapshot=$(ab snapshot -ic 2>/dev/null || echo "(could not capture snapshot)")

  local block
  block="## FAIL: $1
**Error:** $2
**Selector:** ${3:-(none)}
**Page URL:** $url

<snapshot>
$snapshot
</snapshot>

---
"
  # Print to stdout and append to file
  echo "$block"
  echo "$block" >> "$REPORT_FILE"
}

pass() { $QUIET || echo "  ✓ $1"; PASS=$((PASS + 1)); }

fail() {
  # $1 = test name, $2 = error detail, $3 = selector (optional)
  echo "  ✗ $1: $2"
  FAIL=$((FAIL + 1))
  capture_debug "$1" "$2" "${3:-}"
}

section() { $QUIET || echo "$1"; }

assert_visible() {
  if ab is visible "$1" >/dev/null 2>&1; then
    pass "$2"
  else
    fail "$2" "element not visible" "$1"
  fi
}

assert_text_contains() {
  local text
  text=$(ab get text "$1" 2>/dev/null || echo "")
  if echo "$text" | grep -qi "$2"; then
    pass "$3"
  else
    fail "$3" "expected text '$2' but got '$text'" "$1"
  fi
}

assert_enabled() {
  local result
  result=$(ab is enabled "$1" 2>/dev/null || echo "error")
  if [ "$result" = "true" ]; then
    pass "$2"
  else
    fail "$2" "element not enabled (got: $result)" "$1"
  fi
}

assert_disabled() {
  local result
  result=$(ab is enabled "$1" 2>/dev/null || echo "error")
  if [ "$result" = "false" ]; then
    pass "$2"
  else
    fail "$2" "element is enabled (expected disabled, got: $result)" "$1"
  fi
}

cleanup() {
  ab close >/dev/null 2>&1 || true
  # Remove report file if no failures
  if [ "$FAIL" -eq 0 ] && [ -f "$REPORT_FILE" ]; then
    rm "$REPORT_FILE"
  fi
}
trap cleanup EXIT

section "=== xdl-web Integration Tests ==="
section "Base URL: $BASE_URL"
section ""

# ── Download Page ──
section "Download Page"

ab open "$BASE_URL" >/dev/null
ab wait 1000 >/dev/null

assert_visible "h1" "page heading is visible"
assert_text_contains "h1" "x-dl" "heading says x-dl"
assert_visible "form.input-form" "input form is visible"
assert_visible "input[type='url']" "URL input is visible"
assert_visible "button[type='submit']" "submit button is visible"
assert_disabled "button[type='submit']" "submit button disabled when empty"

# Check nav links
assert_visible "a[href='/']" "Download nav link is visible"
assert_visible "a[href='/article']" "Article nav link is visible"
assert_text_contains "nav" "Download" "nav has Download text"
assert_text_contains "nav" "Article" "nav has Article text"

# Submit invalid URL (non-twitter)
ab fill "input[type='url']" "https://example.com/not-a-tweet" >/dev/null
ab click "button[type='submit']" >/dev/null
ab wait 2000 >/dev/null

assert_visible ".status" "status message appears after submit"

section ""

# ── Article Page ──
section "Article Page"

ab click "a[href='/article']" >/dev/null
ab wait 1000 >/dev/null

assert_text_contains ".subtitle" "Article" "article page subtitle"
assert_visible "form.input-form" "article form is visible"
assert_visible "input[type='url']" "article URL input is visible"

# Check placeholder text
placeholder=$(ab eval "document.querySelector('input[type=\"url\"]').placeholder" 2>/dev/null || echo "")
if echo "$placeholder" | grep -qi "video tweet"; then
  pass "article input has video tweet placeholder"
else
  fail "article input has video tweet placeholder" "got: $placeholder" "input[type='url']"
fi

# Check button text
assert_text_contains "button[type='submit']" "Generate" "article button says Generate"

section ""

# ── Navigation ──
section "Navigation"

ab click "a[href='/']" >/dev/null
ab wait 500 >/dev/null
current_url=$(ab get url 2>/dev/null || echo "")
if echo "$current_url" | grep -q "$BASE_URL"; then
  pass "navigate back to download page"
else
  fail "navigate back to download page" "url is: $current_url" "a[href='/']"
fi

ab click "a[href='/article']" >/dev/null
ab wait 500 >/dev/null
current_url=$(ab get url 2>/dev/null || echo "")
if echo "$current_url" | grep -q "/article"; then
  pass "navigate to article page"
else
  fail "navigate to article page" "url is: $current_url" "a[href='/article']"
fi

section ""

# ── Summary ──
echo "=== Results: $PASS passed, $FAIL failed ==="
[ "$FAIL" -gt 0 ] && echo "Failure details: $REPORT_FILE"
[ "$FAIL" -eq 0 ] && exit 0 || exit 1
