#!/usr/bin/env bash
# Integration tests for xdl-web using agent-browser
# Usage: ./test-e2e.sh [-q|--quiet] [base-url]
# Requires: agent-browser, running dev server (bun run dev)

set -euo pipefail

QUIET=false
for arg in "$@"; do
  case "$arg" in
    -q|--quiet) QUIET=true; shift ;;
  esac
done

BASE_URL="${1:-http://localhost:5173}"
SESSION="xdl-web-e2e-$$"
REPORT_FILE="test-e2e-failures.log"
PASS=0
FAIL=0

ab() {
  agent-browser --session "$SESSION" "$@"
}

# Reset the failure report
cat > "$REPORT_FILE" <<'HEADER'
# E2E Test Failure Report
# Generated by test-e2e.sh
# Each failure includes: assertion, selector used, page URL, and a DOM snapshot
# to help diagnose whether the issue is a wrong selector, missing element, or timing bug.
HEADER
echo "# Run: $(date -Iseconds)" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

capture_debug() {
  # $1 = test name, $2 = error detail, $3 = selector (optional)
  local url snapshot
  url=$(ab get url 2>/dev/null || echo "(could not get URL)")
  snapshot=$(ab snapshot -ic 2>/dev/null || echo "(could not capture snapshot)")

  local block
  block="## FAIL: $1
**Error:** $2
**Selector:** ${3:-(none)}
**Page URL:** $url

<snapshot>
$snapshot
</snapshot>

---
"
  # Print to stdout and append to file
  echo "$block"
  echo "$block" >> "$REPORT_FILE"
}

pass() { $QUIET || echo "  ✓ $1"; PASS=$((PASS + 1)); }

fail() {
  # $1 = test name, $2 = error detail, $3 = selector (optional)
  echo "  ✗ $1: $2"
  FAIL=$((FAIL + 1))
  capture_debug "$1" "$2" "${3:-}"
}

section() { $QUIET || echo "$1"; }

assert_visible() {
  if ab is visible "$1" >/dev/null 2>&1; then
    pass "$2"
  else
    fail "$2" "element not visible" "$1"
  fi
}

assert_text_contains() {
  local text
  text=$(ab get text "$1" 2>/dev/null || echo "")
  if echo "$text" | grep -qi "$2"; then
    pass "$3"
  else
    fail "$3" "expected text '$2' but got '$text'" "$1"
  fi
}

assert_enabled() {
  local result
  result=$(ab is enabled "$1" 2>/dev/null || echo "error")
  if [ "$result" = "true" ]; then
    pass "$2"
  else
    fail "$2" "element not enabled (got: $result)" "$1"
  fi
}

assert_disabled() {
  local result
  result=$(ab is enabled "$1" 2>/dev/null || echo "error")
  if [ "$result" = "false" ]; then
    pass "$2"
  else
    fail "$2" "element is enabled (expected disabled, got: $result)" "$1"
  fi
}

cleanup() {
  ab close >/dev/null 2>&1 || true
  # Remove report file if no failures
  if [ "$FAIL" -eq 0 ] && [ -f "$REPORT_FILE" ]; then
    rm "$REPORT_FILE"
  fi
}
trap cleanup EXIT

section "=== xdl-web Integration Tests ==="
section "Base URL: $BASE_URL"
section ""

# ── Download Page ──
section "Download Page"

ab open "$BASE_URL" >/dev/null
ab wait 1000 >/dev/null

assert_visible "h1" "page heading is visible"
assert_text_contains "h1" "x-dl" "heading says x-dl"
assert_visible "form.input-form" "input form is visible"
assert_visible "input[type='url']" "URL input is visible"
assert_visible "button[type='submit']" "submit button is visible"
assert_disabled "button[type='submit']" "submit button disabled when empty"

# Check nav links
assert_visible "a[href='/']" "Download nav link is visible"
assert_visible "a[href='/article']" "Article nav link is visible"
assert_visible "a[href='/pro']" "Pro nav link is visible"
assert_text_contains "nav" "Download" "nav has Download text"
assert_text_contains "nav" "Article" "nav has Article text"

# Submit invalid URL (non-twitter)
ab fill "input[type='url']" "https://example.com/not-a-tweet" >/dev/null
ab click "button[type='submit']" >/dev/null
ab wait 2000 >/dev/null

assert_visible ".status" "status message appears after submit"

section ""

# ── Article Page ──
section "Article Page"

ab click "a[href='/article']" >/dev/null
ab wait 1000 >/dev/null

assert_text_contains ".subtitle" "Article" "article page subtitle"
assert_visible "form.input-form" "article form is visible"
assert_visible "input[type='url']" "article URL input is visible"

# Check placeholder text
placeholder=$(ab eval "document.querySelector('input[type=\"url\"]').placeholder" 2>/dev/null || echo "")
if echo "$placeholder" | grep -qi "video tweet"; then
  pass "article input has video tweet placeholder"
else
  fail "article input has video tweet placeholder" "got: $placeholder" "input[type='url']"
fi

# Check button text
assert_text_contains "button[type='submit']" "Generate" "article button says Generate"

section ""

# ── Video Download (real tweet, m3u8 regression) ──
section "Video Download (real tweet)"

ab click "a[href='/']" >/dev/null
ab wait 1000 >/dev/null

ab fill "input[type='url']" "https://x.com/michaelhyunkim/status/2022004118865506681" >/dev/null
ab click "button[type='submit']" >/dev/null

# Wait for loading status to appear, then poll until it resolves
ab wait 3000 >/dev/null
assert_visible ".status" "download status message appears"

# Poll up to 120s for the download to finish (loading → success or error)
elapsed=0
while [ $elapsed -lt 120 ]; do
  loading=$(ab is visible ".status-loading" 2>/dev/null || echo "false")
  if [ "$loading" = "false" ]; then
    break
  fi
  ab wait 3000 >/dev/null
  elapsed=$((elapsed + 3))
done

# Verify success
success_visible=$(ab is visible ".status-success" 2>/dev/null || echo "false")
if [ "$success_visible" = "true" ]; then
  pass "video download completes successfully"
else
  fail "video download completes successfully" "no .status-success found after ${elapsed}s" ".status-success"
fi

assert_text_contains ".status-success" "downloaded" "success message says downloaded"

# Verify download history appears
assert_visible ".download-history" "download history section is visible"
assert_visible ".history-item" "history item is visible"
assert_text_contains ".history-title" "Recent" "history title says Recent Downloads"

section ""

# ── Re-download Modal ──
section "Re-download Modal"

# Submit same URL again to trigger modal
ab fill "input[type='url']" "https://x.com/michaelhyunkim/status/2022004118865506681" >/dev/null
ab click "button[type='submit']" >/dev/null
ab wait 1000 >/dev/null

assert_visible ".modal-overlay" "re-download modal appears"
assert_text_contains ".modal-content" "Already Downloaded" "modal says Already Downloaded"
assert_text_contains ".modal-content" "Download Again" "modal has Download Again button"
assert_visible ".cancel-btn" "cancel button is visible"

# Close modal
ab click ".cancel-btn" >/dev/null
ab wait 500 >/dev/null

modal_hidden=$(ab is visible ".modal-overlay" 2>/dev/null || echo "false")
if [ "$modal_hidden" = "false" ]; then
  pass "modal closes when cancel clicked"
else
  fail "modal closes when cancel clicked" "modal still visible"
fi

section ""

# ── Article Markdown Rendering ──
section "Article Markdown Rendering"

ab click "a[href='/article']" >/dev/null
ab wait 3000 >/dev/null

ab fill "input[type='url']" "https://x.com/michaelhyunkim/status/2022004118865506681" >/dev/null
ab click "button[type='submit']" >/dev/null

# Poll up to 180s for article generation to complete (steps: download → audio → transcribe → write)
ab wait 5000 >/dev/null
elapsed=0
while [ $elapsed -lt 180 ]; do
  done_visible=$(ab is visible ".article-display" 2>/dev/null || echo "false")
  if [ "$done_visible" = "true" ]; then
    break
  fi
  ab wait 5000 >/dev/null
  elapsed=$((elapsed + 5))
done

assert_visible ".article-display" "article display container is visible"

# Verify markdown was rendered (has heading tags)
has_headings=$(ab eval "!!document.querySelector('.article-display h1, .article-display h2')" 2>/dev/null || echo "false")
if [ "$has_headings" = "true" ]; then
  pass "rendered HTML contains heading tags"
else
  fail "rendered HTML contains heading tags" "no h1/h2 found in article" ".article-display h1, .article-display h2"
fi

assert_visible ".copy-btn" "copy button is visible"

section ""

# ── Pro Page ──
section "Pro Page"

ab click "a[href='/pro']" >/dev/null
ab wait 1000 >/dev/null

assert_visible ".crown-icon" "crown icon is visible"
assert_text_contains "h1" "Pro" "Pro page heading"
assert_visible ".pro-feature-list" "features list is visible"
assert_visible ".pro-cta" "signup CTA is visible"
assert_text_contains ".pro-price-amount" "7.99" 'price shows $7.99'

section ""

# ── Pro Sign-Up Modal ──
section "Pro Sign-Up Modal"

ab click ".pro-cta" >/dev/null
ab wait 1000 >/dev/null

assert_visible ".modal-overlay" "signup modal is visible"
assert_visible ".signup-form" "signup form is visible"
assert_visible ".signup-interests" "interest checkboxes are visible"
assert_visible ".signup-email" "email input is visible"

# Check a feature checkbox
ab click ".signup-checkbox:first-child input" >/dev/null
ab fill ".signup-email" "test@example.com" >/dev/null
ab click "button[type='submit']" >/dev/null
ab wait 2000 >/dev/null

assert_visible ".signup-success" "success message is visible"
assert_text_contains ".signup-success" "notify" "success says notify"

section ""

# Close modal before navigation tests
ab click ".modal-close" >/dev/null 2>&1 || true
ab wait 500 >/dev/null

# ── Navigation ──
section "Navigation"

ab click "a[href='/']" >/dev/null
ab wait 500 >/dev/null
current_url=$(ab get url 2>/dev/null || echo "")
if echo "$current_url" | grep -q "$BASE_URL"; then
  pass "navigate back to download page"
else
  fail "navigate back to download page" "url is: $current_url" "a[href='/']"
fi

ab click "a[href='/article']" >/dev/null
ab wait 500 >/dev/null
current_url=$(ab get url 2>/dev/null || echo "")
if echo "$current_url" | grep -q "/article"; then
  pass "navigate to article page"
else
  fail "navigate to article page" "url is: $current_url" "a[href='/article']"
fi

ab click "a[href='/pro']" >/dev/null
ab wait 500 >/dev/null
current_url=$(ab get url 2>/dev/null || echo "")
if echo "$current_url" | grep -q "/pro"; then
  pass "navigate to pro page"
else
  fail "navigate to pro page" "url is: $current_url" "a[href='/pro']"
fi

section ""

# ── Footer ──
section "Footer"

# Check footer on download page
ab click "a[href='/']" >/dev/null
ab wait 500 >/dev/null

assert_visible ".site-footer" "footer is visible on download page"
assert_text_contains ".site-footer" "Richard Oliver Bray" "footer shows author name"
assert_text_contains ".site-footer" "Report a bug" "footer shows Report a bug link"

# Check footer link
author_link=$(ab eval "document.querySelector('.site-footer a').href" 2>/dev/null || echo "")
if echo "$author_link" | grep -q "RichOBray"; then
  pass "footer links to author X profile"
else
  fail "footer links to author X profile" "got: $author_link" ".site-footer a"
fi

# Check footer on article page
ab click "a[href='/article']" >/dev/null
ab wait 500 >/dev/null
assert_visible ".site-footer" "footer is visible on article page"

# Check footer on pro page
ab click "a[href='/pro']" >/dev/null
ab wait 500 >/dev/null
assert_visible ".site-footer" "footer is visible on pro page"

section ""

# ── Summary ──
echo "=== Results: $PASS passed, $FAIL failed ==="
[ "$FAIL" -gt 0 ] && echo "Failure details: $REPORT_FILE"
[ "$FAIL" -eq 0 ] && exit 0 || exit 1
